export const SUPABASE_URL = 'https://luhuztrjficxxivqypsp.supabase.co';

export const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1aHV6dHJqZmljeHhpdnF5cHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDYwMTU5MjQsImV4cCI6MjAyMTU5MTkyNH0.NoAuUQ_Z_KveaqcUqZMbPuL0y7jIDtj4b0XnZ-_bVAk';
